spring.application.name=tickets

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tickets_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true

# JWT Config
jwt.secret=LsgIn}&a/8N>7X#Z#Feo666crl5&BS}^
jwt.expiration-ms=86400000

# 86400000 ms = 24 horas
# CORS (permite peticiones desde el frontend)
spring.web.cors.allowed-origins=http://localhost:5173
